import * as THREE from 'three';
export const loadingManager = new THREE.LoadingManager();
export const FACE_BASES = [
  { normal: new THREE.Vector3(0, 1, 0), right: new THREE.Vector3(1, 0, 0), forward: new THREE.Vector3(0, 0, -1) }, { normal: new THREE.Vector3(0, -1, 0), right: new THREE.Vector3(1, 0, 0), forward: new THREE.Vector3(0, 0, 1) }, { normal: new THREE.Vector3(0, 0, 1), right: new THREE.Vector3(1, 0, 0), forward: new THREE.Vector3(0, 1, 0) }, { normal: new THREE.Vector3(0, 0, -1), right: new THREE.Vector3(-1, 0, 0), forward: new THREE.Vector3(0, 1, 0) }, { normal: new THREE.Vector3(-1, 0, 0), right: new THREE.Vector3(0, 0, 1), forward: new THREE.Vector3(0, 1, 0) }, { normal: new THREE.Vector3(1, 0, 0), right: new THREE.Vector3(0, 0, -1), forward: new THREE.Vector3(0, 1, 0) },
];
export function pointOnFace(basis, size, right = 0, forward = 0, height = .02) { return basis.normal.clone().multiplyScalar(size / 2 + height).addScaledVector(basis.right, right).addScaledVector(basis.forward, forward); }
export function getFaceAtPosition(p) { const a = [Math.abs(p.y), Math.abs(p.y), Math.abs(p.z), Math.abs(p.z), Math.abs(p.x), Math.abs(p.x)]; let best = 0; for (let i = 1; i < 6; i++) if (a[i] > a[best]) best = i; if ((best === 0 && p.y >= 0) || (best === 1 && p.y < 0) || (best === 2 && p.z >= 0) || (best === 3 && p.z < 0) || (best === 4 && p.x < 0) || (best === 5 && p.x >= 0)) return best; return best ^ 1; }
export function addGround(scene, group, size, basis, color) { const ground = new THREE.Mesh(new THREE.PlaneGeometry(size, size), new THREE.MeshStandardMaterial({ color, roughness: .88, metalness: .04 })); ground.position.copy(pointOnFace(basis, size)); ground.quaternion.setFromUnitVectors(new THREE.Vector3(0, 0, 1), basis.normal); ground.receiveShadow = true; group.add(ground); scene.add(group); }
export function place(object, basis, size, right, forward, height = 0) { object.position.copy(pointOnFace(basis, size, right, forward, height)); object.quaternion.setFromUnitVectors(new THREE.Vector3(0, 1, 0), basis.normal); return object; }
